import { readFile, readdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
const lock = JSON.parse(await readFile('package-lock.json', 'utf8'))
const blocks = ['Books web third-party notices\nIncludes installed build tools as well as browser dependencies.\nGenerated by npm run notices from the locked dependency tree.']
for (const path of Object.keys(lock.packages).filter(p => p.startsWith('node_modules/')).sort()) {
  let pkg, names
  try { pkg = JSON.parse(await readFile(join(path, 'package.json'), 'utf8')); names = await readdir(path) } catch { continue } // Optional platform-specific dependency.
  const licenseFiles = names.filter(n => /^(licen[sc]e|copying|notice|ofl)(\.|$|-)/i.test(n))
  const texts = []
  for (const name of licenseFiles) { try { texts.push(name + '\n' + await readFile(join(path, name), 'utf8')) } catch {} }
  blocks.push(`${pkg.name}@${pkg.version}\nLicense: ${typeof pkg.license === 'string' ? pkg.license : JSON.stringify(pkg.license ?? pkg.licenses ?? 'See upstream')}\nSource: https://www.npmjs.com/package/${pkg.name}/v/${pkg.version}\n${texts.join('\n\n')}`)
}
await writeFile('public/THIRD_PARTY_NOTICES.txt', (blocks.join('\n\n' + '='.repeat(72) + '\n\n') + '\n').replace(/\r\n/g, '\n').replace(/[ \t]+$/gm, ''))
console.log(`Retained notices for ${blocks.length - 1} installed packages.`)
